// AUTH
export const AUTO_LOGIN_REQUEST = "AUTO_LOGIN_REQUEST";
export const AUTO_LOGIN_SUCCESS = "AUTO_LOGIN_SUCCESS";
export const AUTO_LOGIN_FAILURE = "AUTO_LOGIN_FAILURE";
export const AUTO_LOGIN_RESET = "AUTO_LOGIN_RESET";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_RESET = "LOGIN_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";

// INSTRUCTOR
export const GET_INSTRUCTORS = "GET_INSTRUCTORS";
export const SET_INSTRUCTORS = "SET_INSTRUCTORS";

export const GET_INSTRUCTOR_DETAIL = "GET_INSTRUCTOR_DETAIL";
export const SET_INSTRUCTOR_DETAIL = "SET_INSTRUCTOR_DETAIL";

export const CONFIRM_INSTRUCTOR = "CONFIRM_INSTRUCTOR";
export const CANCEL_INSTRUCTOR = "CANCEL_INSTRUCTOR";

// STUDENT
export const GET_STUDENTS = "GET_STUDENTS";
export const SET_STUDENTS = "SET_STUDENTS";

// SHAPE
export const GET_SHAPES = "GET_SHAPES";
export const SET_SHAPES = "SET_SHAPES";

export const GET_SHAPE_DETAIL_REQUEST = "GET_SHAPE_DETAIL_REQUEST";
export const GET_SHAPE_DETAIL_FINISHED = "GET_SHAPE_DETAIL_FINISHED";

export const CREATE_SHAPE_REQUEST = "CREATE_SHAPE_REQUEST";
export const CREATE_SHAPE_FINISHED = "CREATE_SHAPE_FINISHED";

export const UPDATE_SHAPE_REQUEST = "UPDATE_SHAPE_REQUEST";
export const UPDATE_SHAPE_FINISHED = "UPDATE_SHAPE_FINISHED";

// QUESTION
export const GET_QUESTIONS = "GET_QUESTIONS";
export const SET_QUESTIONS = "SET_QUESTIONS";

// SETTINGS
export const GET_QUESTION_CONFIGS_REQUEST = "GET_QUESTION_CONFIGS_REQUEST";
export const GET_QUESTION_CONFIGS_FINISHED = "GET_QUESTION_CONFIGS_FINISHED";

export const CREATE_DURATION_REQUEST = "CREATE_DURATION_REQUEST";
export const CREATE_DURATION_FINISHED = "CREATE_DURATION_FINISHED";

export const ACTIVATE_DURATION = "ACTIVATE_DURATION";
export const DEACTIVATE_DURATION = "DEACTIVATE_DURATION";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_FINISHED = "CREATE_CATEGORY_FINISHED";

export const ACTIVATE_CATEGORY = "ACTIVATE_CATEGORY";
export const DEACTIVATE_CATEGORY = "DEACTIVATE_CATEGORY";

export const CREATE_GRADE_REQUEST = "CREATE_GRADE_REQUEST";
export const CREATE_GRADE_FINISHED = "CREATE_GRADE_FINISHED";

export const ACTIVATE_GRADE = "ACTIVATE_GRADE";
export const DEACTIVATE_GRADE = "DEACTIVATE_GRADE";

// SOFTWARE
export const SYNC_SEARCHES = "SYNC_SEARCHES";
